networks:
  app-network:
    name: zti-network
    external: true
    driver: bridge

services:
  react:
    build:
      context: ./frontend_new
    ports:
      - "5175:80"
    networks:
      - app-network
    container_name: react

  springboot:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
    container_name: springboot
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
